jobs:
- job: macOS
  displayName: macOS-10.15
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes yes
      conda install -n root conda-build numpy fftw
    displayName: Set up Anaconda

  - bash: |
      conda build --python $PYTHON_VERSION ./conf
    displayName: Build and test

- job: Ubuntu
  displayName: Ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes yes
      conda install -n root conda-build numpy fftw
    displayName: Set up Anaconda

  - bash: |
      conda build --no-test --python $PYTHON_VERSION ./conf
      conda create --name mpi4py_fft_env mpi4py_fft_test coverage scipy pyfftw python=$PYTHON_VERSION --use-local
      source activate mpi4py_fft_env
      pip install codecov codacy-coverage
      cd tests && ./runtests.sh
    displayName: Build and test

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - bash: |
      if [ $PYTHON_VERSION == 3.7 ]; then
        source activate mpi4py_fft_env
        cd tests
        codecov -t $(CODECOV_TOKEN)
        #curl -s -o codecov.sh https://codecov.io/bash
        #bash codecov.sh -X gcov -X fix -t $(CODECOV_TOKEN)
        python-codacy-coverage -r coverage.xml -t $(CODACY_PROJECT_TOKEN)
      fi
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Upload to Codecov
