image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        script:
          - conda config --set always_yes yes
          - conda config --add channels conda-forge
          - conda config --add channels spectralDNS
          - conda install -n root conda-build=3.17
          - conda build conf/
