image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        script:
          - conda config --set always_yes yes
          - conda config --add channels conda-forge
          - conda install -n root conda-build numpy fftw
          - conda build conf/
