version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v1-miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            if [[ ! -d /home/circleci/miniconda ]]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh &&
                bash miniconda.sh -b -f -p /home/circleci/miniconda;
            else
                echo "Using cached miniconda";
            fi
            source ~/miniconda/bin/activate root
            conda config --set always_yes yes
            conda update -q conda
            conda config --add channels conda-forge
            conda install -n root conda-build
            #conda install --yes --quiet conda-forge-build-setup
            #source run_conda_forge_build_setup

      - save_cache:
          key: v1-miniconda-{{ .Branch }}
          paths:
            - /home/circleci/miniconda

      - run:
          name: Build and test Python 2.7
          command: |
            source ~/miniconda/bin/activate root
            conda build --python 2.7 ./conf

      - run:
          name: Build and test Python 3.6
          command: |
            source ~/miniconda/bin/activate root
            conda build --python 3.6 ./conf

        
      #- run:
      #    name: Upload packages
      #    command: |
      #        source ~/miniconda/bin/activate root
      #        cd /home/circleci/project
      #        upload_or_check_non_existence ./conf mpi4py --channel main
      #        export CONDA_PY=36
      #        upload_or_check_non_existence ./conf mpi4py --channel main

