version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v2-miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            if [[ ! -d /home/circleci/miniconda ]]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh &&
                bash miniconda.sh -b -f -p /home/circleci/miniconda;
            else
                echo "Using cached miniconda";
            fi
            source ~/miniconda/bin/activate root
            conda config --set always_yes yes
            conda update -q conda
            conda config --add channels conda-forge
            conda install -n root conda-build coverage codecov
            pip install --no-deps codacy-coverage

      - run:
          name: Build and test Python 3.6
          command: |
            source ~/miniconda/bin/activate root
            conda build --no-test --python 3.6 ./conf
            conda install mpi4py_fft --use-local
            cd tests && ./runtests.sh

      - run:
          name: Build and test Python 2.7
          command: |
            source ~/miniconda/bin/activate root
            conda build --python 2.7 ./conf

      - deploy:
          name: Deploy
          command: |
            source ~/miniconda/bin/activate root
            cd tests
            curl -s -o codecov.sh https://codecov.io/bash
            bash codecov.sh -X gcov -X fix
            coverage xml
            python-codacy-coverage -r coverage.xml
           
      - save_cache:
          key: v2-miniconda-{{ .Branch }}
          paths:
            - /home/circleci/miniconda

