package:
  name: mpi4py_fft
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../
  #git_url: https://bitbucket.org/mpi4py/mpi4py-fft
  #git_tag: master

build:
  number: 2000

requirements:
  build:
    - python
    - cython
    - mpi4py
    - {{ mpi }}
    - numpy
    - nomkl
    - pip
    - fftw
    - setuptools

  run:
    - python
    - mpi4py
    - {{ mpi }}
    - numpy
    - fftw
    - pyfftw
    - nomkl
    - scipy >=1.0.0
    - hdf5 1.10.4 mpi_{{ mpi }}_*
    - h5py 2.9.0 mpi_{{ mpi }}_*
    - netcdf4-parallel

test:
  requires:
    - coverage # [py3k]
    - codecov # [py3k]
    - scipy >=1.0.0

  source_files:
    - tests

  imports:
    - mpi4py_fft
