package:
  name: mpi4py_fft
  version: "1.0.0"

source:
  git_url: ../
  #git_url: https://bitbucket.org/mpi4py/mpi4py-fft
  #git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - mpi4py
    - numpy >=1.15.1
    - six
    - pip
    - fftw

  run:
    - python
    - mpi4py
    - numpy >=1.15.1
    - fftw
    - pyfftw
    - six
    - scipy >=1.1.0

test:
  requires:
    - coverage # [py3k]
    - codecov # [py3k]

  source_files:
    - tests

  imports:
    - mpi4py_fft

