{% set data = load_setup_py_data() %}

package:
  name: mpi4py_fft
  version: {{ data.get('version') }}

source:
  git_url: ../
  #git_url: https://bitbucket.org/mpi4py/mpi4py-fft
  #git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - mpi4py
    - numpy
    - nomkl
    - pip
    - fftw
    - setuptools

  run:
    - python
    - mpi4py
    - numpy
    - fftw
    - pyfftw
    - nomkl
    - scipy >=1.0.0
    - h5py-parallel
    - netcdf4-parallel

test:
  requires:
    - coverage # [py3k]
    - codecov # [py3k]
    - scipy >=1.0.0

  source_files:
    - tests

  imports:
    - mpi4py_fft
